# _config.yml
title: "EZ Foam Website"
url: "https://github.com/ezfoam/ezfoamwebsite/" # Replace with your GitHub Pages URL or custom domain
baseurl: ""                          # Leave empty for a user site or specify a subpath for project pages
timezone: "America/Denver"           # Update to your local timezone

# Author details
author:
  name: "Jose Dominguez"
  email: "ezfoam@outlook.com"

# Markdown and Code Highlighting
markdown: kramdown
highlighter: rouge
permalink: pretty

# Theme-specific settings (adjust these based on the theme documentation)
logo: "/assets/img/logo.png"         # Update or remove if not needed
favicon: "/assets/img/favicon.ico"     # Update or remove if not needed
google_analytics: "UA-XXXXXX-X"        # Replace with your tracking code, or remove this line

# Navigation Menu (if the theme supports it)
nav_items:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

# Do not exclude the CMS admin folder so that it gets published
# You can optionally include it explicitly:
include:
  - admin
