# admin/config.yml
backend:
  name: github
  branch: main   # or your default branch name (e.g., master)
  repo: ezfoam/ezfoamwebsite  # This points to your fork/repository

media_folder: "assets/img"   # Uploaded images will be stored here
public_folder: "/assets/img" # Public path for media files

collections:
  - name: "pages"
    label: "Pages"
    folder: ""               # An empty string means Netlify CMS will manage files in the root. 
                              # If your pages are in a subfolder (e.g. _pages), update this value.
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
