# admin/config.yml
backend:
  name: github
  branch: master   # or your default branch name (e.g., master)
  repo: ezfoam/ezfoamwebsite  # This points to your fork/repository

media_folder: "assets/img"   # Uploaded images will be stored here
public_folder: "/assets/img" # Public path for media files

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"         # Use "_pages" if your content is organized in that folder
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
