backend:
  name: github
  branch: master             # or main, depending on your default branch
  repo: ezfoam/ezfoamwebsite

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"         # Ensure that you store your non-blog pages here
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Slug", name: "slug", widget: "string", default: "" }   # optional custom slug field
